services:
  unicorn-backend:
    build:
      context: .
    container_name: unicorn-backend
    restart: always
    ports:
      - 3000:3000
    networks:
      - unicorn-backend

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    networks:
      - unicorn-backend
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      - MY_URL=${BACKEND_URL:-}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_config:
  caddy_data:

networks:
  unicorn-backend:
    name: unicorn-backend
    external: true