name: deploy-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Redeploy Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd unicorn-backend
            docker compose down
            git checkout main
            git reset --hard HEAD~1
            git pull origin main
            docker image prune -a --force
            docker compose build --no-cache
            docker compose up -d --build